# Generated by Django 5.1.2 on 2025-07-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Номер телефона')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='participants')),
                ('location', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('voter_fingerprint', models.CharField(max_length=255)),
                ('voter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='authentication.participant')),
            ],
            options={
                'unique_together': {('participant', 'voter_fingerprint', 'voter_ip')},
            },
        ),
    ]
